lab-3/config/routes.rb
Rails.application.routes.draw do

  scope :traffic, :controller => :camera_search do

    get :new, :as => :new_camera_search
    get :results, :as => :camera_search_results

    resources :traffic_cameras

  end
end

lab-3/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

lab-3/app/models/traffic_camera.rb
# == Schema Information
# Schema version: 20190731213625
#
# Table name: traffic_cameras
#
#  id             :bigint           not null, primary key
#  name           :text
#  latitude       :decimal(, )
#  longitude      :decimal(, )
#  is_operational :boolean
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

require 'haversine'
require 'geocoder'

class TrafficCamera < ApplicationRecord
  validates :id, :name, :latitude, :longitude, :is_operational, presence: true
  validates :name, uniqueness: true
  validates :latitude, :inclusion => -90...90
  validates :longitude, :inclusion => -180...180

  def distance_to(lat, lon)

    Haversine.distance(lat, lon, self.latitude, self.longitude).to_miles

  end

  def self.closest_active_camera(lat, lon)
    distances = []

    TrafficCamera.all.each do |traffic_camera|
      distance = traffic_camera.distance_to(lat, lon)
      distances << distance
    end

    TrafficCamera.all.map{|c| [c, c.distance_to(lat,lon)] }.min_by{|v| v[1]}[0]
  end
end

lab-3/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

lab-3/app/controllers/camera_search_controller.rb
# require 'traffic_module'

# this comment only exists to satisfy the linter
class CameraSearchController < ApplicationController
  def new
    # Nothing to do here.
  end

  def results
    result = Geocoder.search(params[:query]).first
    if result.nil?
      # Geocoding was not successful.
      @traffic_camera = nil
      @distance = nil
    else
      data = result.data
      query_latitude = data['lat'].to_f; query_longitude = data['lon'].to_f
      @traffic_camera = TrafficCamera.closest_active_camera(query_latitude,query_longitude)
      @distance = @traffic_camera.distance_to(query_latitude,query_longitude)
    end
  end

end

lab-3/app/controllers/traffic_cameras_controller.rb
class TrafficCamerasController < ApplicationController
  before_action :set_traffic_camera, only: [:show, :edit, :update, :destroy]

  # GET /traffic_cameras
  # GET /traffic_cameras.json
  def index
    @traffic_cameras = TrafficCamera.all
  end

  # GET /traffic_cameras/1
  # GET /traffic_cameras/1.json
  def show
  end

  # GET /traffic_cameras/new
  def new
    @traffic_camera = TrafficCamera.new
  end

  # GET /traffic_cameras/1/edit
  def edit
  end

  # POST /traffic_cameras
  # POST /traffic_cameras.json
  def create
    @traffic_camera = TrafficCamera.new(traffic_camera_params)

    respond_to do |format|
      if @traffic_camera.save
        format.html { redirect_to @traffic_camera, notice: 'Traffic camera was successfully created.' }
        format.json { render :show, status: :created, location: @traffic_camera }
      else
        format.html { render :new }
        format.json { render json: @traffic_camera.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /traffic_cameras/1
  # PATCH/PUT /traffic_cameras/1.json
  def update
    respond_to do |format|
      if @traffic_camera.update(traffic_camera_params)
        format.html { redirect_to @traffic_camera, notice: 'Traffic camera was successfully updated.' }
        format.json { render :show, status: :ok, location: @traffic_camera }
      else
        format.html { render :edit }
        format.json { render json: @traffic_camera.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /traffic_cameras/1
  # DELETE /traffic_cameras/1.json
  def destroy
    @traffic_camera.destroy
    respond_to do |format|
      format.html { redirect_to traffic_cameras_url, notice: 'Traffic camera was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_traffic_camera
      @traffic_camera = TrafficCamera.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def traffic_camera_params
      params.require(:traffic_camera).permit(:latitude, :longitude, :name, :is_operational)
    end
end

lab-3/app/helpers/application_helper.rb
module ApplicationHelper
end

lab-3/app/helpers/camera_search_helper.rb
module CameraSearchHelper
end

lab-3/app/helpers/traffic_cameras_helper.rb
module TrafficCamerasHelper
end

lab-3/app/views/camera_search/new.html.erb
<div class="queryBar">
  <%= form_tag camera_search_results_path, :method => :get do %>
    Enter Your Query Address: <%= text_field_tag :query %>
    <br>
  <%= submit_tag "Submit", :method => :get do %>
    <%end %>
  <% end %>
</div>

lab-3/app/views/camera_search/results.html.erb
<h3>Query: <%= params[:query] %></h3>
<br>
<br>
<b>Result:</b> <%= @traffic_camera.name %>
<br>
<b>Distance:</b> <%= @distance %> miles!
<br/>
<br>
<%= link_to 'Try Another Search', new_camera_search_path %>

lab-3/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lab3: Traffic Camera</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

lab-3/app/views/traffic_cameras/_form.html.erb
<%= form_with(model: traffic_camera, local: true) do |form| %>
  <% if traffic_camera.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(traffic_camera.errors.count, "error") %> prohibited this traffic_camera from being saved:</h2>

      <ul>
      <% traffic_camera.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :latitude %>
    <%= form.text_field :latitude %>
  </div>

  <div class="field">
    <%= form.label :longitude %>
    <%= form.text_field :longitude %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_area :name %>
  </div>

  <div class="field">
    <%= form.label :is_operational %>
    <%= form.check_box :is_operational %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

lab-3/app/views/traffic_cameras/edit.html.erb
<h1>Editing Traffic Camera</h1>

<%= render 'form', traffic_camera: @traffic_camera %>

<%= link_to 'Show', @traffic_camera %> |
<%= link_to 'Back', traffic_cameras_path %>

lab-3/app/views/traffic_cameras/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Traffic Cameras</h1>

<table>
  <thead>
    <tr>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Name</th>
      <th>Is operational</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @traffic_cameras.each do |traffic_camera| %>
      <tr>
        <td><%= traffic_camera.latitude %></td>
        <td><%= traffic_camera.longitude %></td>
        <td><%= traffic_camera.name %></td>
        <td><%= traffic_camera.is_operational %></td>
        <td><%= link_to 'Show', traffic_camera %></td>
        <td><%= link_to 'Edit', edit_traffic_camera_path(traffic_camera) %></td>
        <td><%= link_to 'Destroy', traffic_camera, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Traffic Camera', new_traffic_camera_path %>

lab-3/app/views/traffic_cameras/new.html.erb
<h1>New Traffic Camera</h1>

<%= render 'form', traffic_camera: @traffic_camera %>

<%= link_to 'Back', traffic_cameras_path %>

lab-3/app/views/traffic_cameras/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Latitude:</strong>
  <%= @traffic_camera.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @traffic_camera.longitude %>
</p>

<p>
  <strong>Name:</strong>
  <%= @traffic_camera.name %>
</p>

<p>
  <strong>Is operational:</strong>
  <%= @traffic_camera.is_operational %>
</p>

<%= link_to 'Edit', edit_traffic_camera_path(@traffic_camera) %> |
<%= link_to 'Back', traffic_cameras_path %>